name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          region: us-east-1
      
      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --exclude "config.js"

            